id: ep_35iyiDOELLBZqWI4pRiT6Y3NraT
url: "https://gh-action-test-endpoint.ngrok.dev:443"
type: "cloud"
description: "Created by a GitHub Action"
metadata: "github.com/iambmelt/Traffic-Policy-Git-Demo"
pooling_enabled: false
